version: "3.9"

x-app-environment: &x-app-environment
  # HTTP
  HTTP_PORT: "8080"

services:
  quotes:
    build:
      context: .
    container_name: quotes_service
    environment:
      <<: *x-app-environment
    ports:
      - "8080:8080"